# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K0qtwcaxZgBA1DJfO1k6dNm9zrq6_GHm
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
movies=pd.read_csv('/content/drive/MyDrive/tmdb_movies_data.csv')

movies.head(5)

movies.describe()

movies.info()

movies.isnull().sum()

movies.columns

movies=movies[['id','original_title','overview','genres']]

movies

movies['tags']=movies['overview']+movies['genres']

movies

new_data=movies.drop(columns=['overview','genres'])

new_data

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=10000,stop_words='english')

from sklearn.metrics.pairwise import cosine_similarity

cv

vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

vector.shape

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vector)

similarity

new_data[new_data['original_title']=='The Godfather'].index[0]

distance=sorted(list(enumerate(similarity[7269])),reverse=True,key=lambda vector:vector[1])
for i in distance[0:5]:
  print(new_data.iloc[i[0]].original_title)

def recomend(movies):
  index=new_data[new_data['original_title']==movies].index[0]
  distance=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda vector:vector[1])
  for i in distance[0:5]:
    print(new_data.iloc[i[0]].original_title)

recomend("Iron Man")

import pickle

pickle.dump(new_data,open('movies_list.pkl','wb'))

pickle.dump(similarity,open('similarity.pkl','wb'))

pickle.load(open('movies_list.pkl','rb'))

